import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface CalculatorResult {
  investment: number;
  contextScore: number;
  resistanceScore: number;
  beneficiaries: number;
  duration: number;
  sRoi: string;
  socialValue: number;
  impactScore: number;
  rating: string;
  language?: string;
}

const translations = {
  pt: {
    title: 'RELATÓRIO DE IMPACTO SOCIAL',
    subtitle: 'Calculadora S-ROI - Método IMPACT7',
    generatedAt: 'Gerado em',
    projectData: 'Dados do Projeto',
    investment: 'Investimento Total',
    contextAlignment: 'Alinhamento de Contexto',
    barriers: 'Barreiras e Resistência',
    beneficiaries: 'Beneficiários Diretos',
    duration: 'Duração do Projeto',
    months: 'meses',
    results: 'Resultados da Análise',
    sRoi: 'S-ROI Estimado',
    socialValue: 'Valor Social Gerado',
    impactScore: 'Score de Impacto',
    classification: 'Classificação',
    equation: 'A Equação do Impacto',
    equationDesc: 'I = (E × C⁷) / R',
    equationExplanation: 'Onde E = Energia (Investimento), C = Contexto (Alinhamento), R = Resistência (Barreiras)',
    benchmarks: 'Benchmarks de Referência',
    minRecommended: 'S-ROI Mínimo Recomendado',
    avgSocial: 'S-ROI Médio (Projetos Sociais)',
    top10: 'Top 10% S-ROI (IMPACT7)',
    methodology: 'Metodologia',
    methodologyDesc: 'Este relatório foi gerado utilizando o Método IMPACT7, que combina Ciência Cognitiva, Modelagem Matemática e Engenharia de Software para maximizar o retorno sobre investimento social.',
    footer: 'Relatório gerado automaticamente pela Plataforma IMPACT7',
    disclaimer: 'Os valores apresentados são estimativas baseadas nos dados fornecidos e podem variar conforme a execução do projeto.',
  },
  en: {
    title: 'SOCIAL IMPACT REPORT',
    subtitle: 'S-ROI Calculator - IMPACT7 Method',
    generatedAt: 'Generated at',
    projectData: 'Project Data',
    investment: 'Total Investment',
    contextAlignment: 'Context Alignment',
    barriers: 'Barriers and Resistance',
    beneficiaries: 'Direct Beneficiaries',
    duration: 'Project Duration',
    months: 'months',
    results: 'Analysis Results',
    sRoi: 'Estimated S-ROI',
    socialValue: 'Social Value Generated',
    impactScore: 'Impact Score',
    classification: 'Classification',
    equation: 'The Impact Equation',
    equationDesc: 'I = (E × C⁷) / R',
    equationExplanation: 'Where E = Energy (Investment), C = Context (Alignment), R = Resistance (Barriers)',
    benchmarks: 'Reference Benchmarks',
    minRecommended: 'Minimum Recommended S-ROI',
    avgSocial: 'Average S-ROI (Social Projects)',
    top10: 'Top 10% S-ROI (IMPACT7)',
    methodology: 'Methodology',
    methodologyDesc: 'This report was generated using the IMPACT7 Method, which combines Cognitive Science, Mathematical Modeling, and Software Engineering to maximize social return on investment.',
    footer: 'Report automatically generated by IMPACT7 Platform',
    disclaimer: 'The values presented are estimates based on the data provided and may vary according to project execution.',
  },
  es: {
    title: 'INFORME DE IMPACTO SOCIAL',
    subtitle: 'Calculadora S-ROI - Método IMPACT7',
    generatedAt: 'Generado en',
    projectData: 'Datos del Proyecto',
    investment: 'Inversión Total',
    contextAlignment: 'Alineación de Contexto',
    barriers: 'Barreras y Resistencia',
    beneficiaries: 'Beneficiarios Directos',
    duration: 'Duración del Proyecto',
    months: 'meses',
    results: 'Resultados del Análisis',
    sRoi: 'S-ROI Estimado',
    socialValue: 'Valor Social Generado',
    impactScore: 'Puntuación de Impacto',
    classification: 'Clasificación',
    equation: 'La Ecuación del Impacto',
    equationDesc: 'I = (E × C⁷) / R',
    equationExplanation: 'Donde E = Energía (Inversión), C = Contexto (Alineación), R = Resistencia (Barreras)',
    benchmarks: 'Benchmarks de Referencia',
    minRecommended: 'S-ROI Mínimo Recomendado',
    avgSocial: 'S-ROI Promedio (Proyectos Sociales)',
    top10: 'Top 10% S-ROI (IMPACT7)',
    methodology: 'Metodología',
    methodologyDesc: 'Este informe fue generado utilizando el Método IMPACT7, que combina Ciencia Cognitiva, Modelado Matemático e Ingeniería de Software para maximizar el retorno sobre inversión social.',
    footer: 'Informe generado automáticamente por la Plataforma IMPACT7',
    disclaimer: 'Los valores presentados son estimaciones basadas en los datos proporcionados y pueden variar según la ejecución del proyecto.',
  },
};

export function generateCalculatorPDF(data: CalculatorResult): string {
  const lang = (data.language || 'en') as keyof typeof translations;
  const t = translations[lang] || translations.en;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primaryColor: [number, number, number] = [255, 107, 53]; // Orange
  const darkColor: [number, number, number] = [30, 41, 59]; // Dark blue
  const grayColor: [number, number, number] = [107, 114, 128];
  
  // Header
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(t.title, pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(200, 200, 200);
  doc.text(t.subtitle, pageWidth / 2, 30, { align: 'center' });
  
  doc.setFontSize(10);
  doc.text(`${t.generatedAt}: ${new Date().toLocaleString(lang === 'pt' ? 'pt-BR' : lang === 'es' ? 'es-ES' : 'en-US')}`, pageWidth / 2, 40, { align: 'center' });
  
  // Project Data Section
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.projectData, 20, 60);
  
  const formatCurrency = (value: number) => {
    const locale = lang === 'pt' ? 'pt-BR' : lang === 'es' ? 'es-ES' : 'en-US';
    const currency = lang === 'pt' ? 'BRL' : 'USD';
    return new Intl.NumberFormat(locale, { style: 'currency', currency, minimumFractionDigits: 0 }).format(value);
  };
  
  autoTable(doc, {
    startY: 65,
    head: [],
    body: [
      [t.investment, formatCurrency(data.investment)],
      [t.contextAlignment, `${data.contextScore}/10`],
      [t.barriers, `${data.resistanceScore}/10`],
      [t.beneficiaries, data.beneficiaries.toLocaleString()],
      [t.duration, `${data.duration} ${t.months}`],
    ],
    theme: 'plain',
    styles: { fontSize: 11 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 80 },
      1: { halign: 'right' },
    },
    margin: { left: 20, right: 20 },
  });
  
  // Results Section
  const resultsY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.results, 20, resultsY);
  
  // S-ROI Highlight Box
  doc.setFillColor(255, 247, 237); // Light orange background
  doc.roundedRect(20, resultsY + 5, pageWidth - 40, 35, 3, 3, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(...grayColor);
  doc.text(t.sRoi, pageWidth / 2, resultsY + 15, { align: 'center' });
  
  doc.setFontSize(28);
  doc.setTextColor(...primaryColor);
  doc.text(`${data.sRoi}x`, pageWidth / 2, resultsY + 30, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(...darkColor);
  doc.text(data.rating, pageWidth / 2, resultsY + 38, { align: 'center' });
  
  // Other Results
  autoTable(doc, {
    startY: resultsY + 50,
    head: [],
    body: [
      [t.socialValue, formatCurrency(data.socialValue)],
      [t.impactScore, data.impactScore.toLocaleString()],
    ],
    theme: 'plain',
    styles: { fontSize: 11 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 80 },
      1: { halign: 'right' },
    },
    margin: { left: 20, right: 20 },
  });
  
  // Equation Section
  const equationY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.equation, 20, equationY);
  
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(20, equationY + 5, pageWidth - 40, 25, 3, 3, 'F');
  
  doc.setFontSize(16);
  doc.setTextColor(...primaryColor);
  doc.text(t.equationDesc, pageWidth / 2, equationY + 15, { align: 'center' });
  
  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  doc.text(t.equationExplanation, pageWidth / 2, equationY + 25, { align: 'center' });
  
  // Benchmarks Section
  const benchmarksY = equationY + 40;
  
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.benchmarks, 20, benchmarksY);
  
  autoTable(doc, {
    startY: benchmarksY + 5,
    head: [],
    body: [
      [t.minRecommended, '7x'],
      [t.avgSocial, '3-4x'],
      [t.top10, '12x+'],
    ],
    theme: 'striped',
    styles: { fontSize: 10 },
    headStyles: { fillColor: primaryColor },
    columnStyles: {
      0: { cellWidth: 120 },
      1: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 20, right: 20 },
  });
  
  // Methodology Section
  const methodY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.methodology, 20, methodY);
  
  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  const methodLines = doc.splitTextToSize(t.methodologyDesc, pageWidth - 40);
  doc.text(methodLines, 20, methodY + 8);
  
  // Disclaimer
  const disclaimerY = methodY + 8 + (methodLines.length * 4) + 10;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const disclaimerLines = doc.splitTextToSize(t.disclaimer, pageWidth - 40);
  doc.text(disclaimerLines, 20, disclaimerY);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...grayColor);
  doc.text(
    t.footer,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );
  
  // Return as data URI
  return doc.output('datauristring');
}

export function generateCalculatorPDFBuffer(data: CalculatorResult): Buffer {
  const lang = (data.language || 'en') as keyof typeof translations;
  const t = translations[lang] || translations.en;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primaryColor: [number, number, number] = [255, 107, 53];
  const darkColor: [number, number, number] = [30, 41, 59];
  const grayColor: [number, number, number] = [107, 114, 128];
  
  // Header
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(t.title, pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(200, 200, 200);
  doc.text(t.subtitle, pageWidth / 2, 30, { align: 'center' });
  
  doc.setFontSize(10);
  doc.text(`${t.generatedAt}: ${new Date().toLocaleString(lang === 'pt' ? 'pt-BR' : lang === 'es' ? 'es-ES' : 'en-US')}`, pageWidth / 2, 40, { align: 'center' });
  
  // Project Data
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.projectData, 20, 60);
  
  const formatCurrency = (value: number) => {
    const locale = lang === 'pt' ? 'pt-BR' : lang === 'es' ? 'es-ES' : 'en-US';
    const currency = lang === 'pt' ? 'BRL' : 'USD';
    return new Intl.NumberFormat(locale, { style: 'currency', currency, minimumFractionDigits: 0 }).format(value);
  };
  
  autoTable(doc, {
    startY: 65,
    head: [],
    body: [
      [t.investment, formatCurrency(data.investment)],
      [t.contextAlignment, `${data.contextScore}/10`],
      [t.barriers, `${data.resistanceScore}/10`],
      [t.beneficiaries, data.beneficiaries.toLocaleString()],
      [t.duration, `${data.duration} ${t.months}`],
    ],
    theme: 'plain',
    styles: { fontSize: 11 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 80 },
      1: { halign: 'right' },
    },
    margin: { left: 20, right: 20 },
  });
  
  // Results
  const resultsY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.setTextColor(...darkColor);
  doc.text(t.results, 20, resultsY);
  
  doc.setFillColor(255, 247, 237);
  doc.roundedRect(20, resultsY + 5, pageWidth - 40, 35, 3, 3, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(...grayColor);
  doc.text(t.sRoi, pageWidth / 2, resultsY + 15, { align: 'center' });
  
  doc.setFontSize(28);
  doc.setTextColor(...primaryColor);
  doc.text(`${data.sRoi}x`, pageWidth / 2, resultsY + 30, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(...darkColor);
  doc.text(data.rating, pageWidth / 2, resultsY + 38, { align: 'center' });
  
  autoTable(doc, {
    startY: resultsY + 50,
    head: [],
    body: [
      [t.socialValue, formatCurrency(data.socialValue)],
      [t.impactScore, data.impactScore.toLocaleString()],
    ],
    theme: 'plain',
    styles: { fontSize: 11 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 80 },
      1: { halign: 'right' },
    },
    margin: { left: 20, right: 20 },
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...grayColor);
  doc.text(
    t.footer,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );
  
  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}
