ALTER TABLE `apiKeys` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `ebookDownloads` MODIFY COLUMN `emailSent` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `featureFlags` MODIFY COLUMN `isEnabled` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `featureFlags` MODIFY COLUMN `isExperiment` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `jarvisAnalytics` MODIFY COLUMN `successful` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `jarvisMemory` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `knowledgeDocuments` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `leads` MODIFY COLUMN `welcomeEmailSent` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `leads` MODIFY COLUMN `unsubscribed` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `newsletterSubscribers` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `infoEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `successEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `warningEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `errorEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `casePendingEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `caseApprovedEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `caseRejectedEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `certificateIssuedEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `tokenEarnedEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `systemEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `emailEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationPreferences` MODIFY COLUMN `pushEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationTemplates` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `notificationTemplates` MODIFY COLUMN `isSystem` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `notifications` MODIFY COLUMN `isRead` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `oauthClients` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `partners` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `partners` MODIFY COLUMN `isFeatured` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `referrals` MODIFY COLUMN `referrerRewardApplied` int DEFAULT 0;--> statement-breakpoint
ALTER TABLE `referrals` MODIFY COLUMN `referredRewardApplied` int DEFAULT 0;--> statement-breakpoint
ALTER TABLE `set7Gates` MODIFY COLUMN `humanApprovalRequired` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `set7RuntimeConfig` MODIFY COLUMN `hookRoiEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `set7RuntimeConfig` MODIFY COLUMN `hookTokensEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `set7RuntimeConfig` MODIFY COLUMN `hookQualityEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `set7RuntimeConfig` MODIFY COLUMN `hookSecurityEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `set7RuntimeConfig` MODIFY COLUMN `hookGtlEnabled` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `set7RuntimeConfig` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `set7TokenBudgets` MODIFY COLUMN `circuitBreakerTriggered` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `socialProofMetrics` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `testimonials` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `testimonials` MODIFY COLUMN `isFeatured` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `ticketMessages` MODIFY COLUMN `isStaff` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `twoFactorAuth` MODIFY COLUMN `isEnabled` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `twoFactorAuth` MODIFY COLUMN `isVerified` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `twoFactorSessions` MODIFY COLUMN `isVerified` int NOT NULL DEFAULT 0;--> statement-breakpoint
ALTER TABLE `userAccessTokens` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `userPreferences` MODIFY COLUMN `emailNotifications` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `userPreferences` MODIFY COLUMN `pushNotifications` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `userPreferences` MODIFY COLUMN `weeklyDigest` int NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `webhooks` MODIFY COLUMN `isActive` int NOT NULL DEFAULT 1;